# Generated by Django 6.1.1 on 2026-10-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merch',
            old_name='price',
            new_name='adult_price',
        ),
        migrations.AddField(
            model_name='merch',
            name='child_price',
            field=models.PositiveIntegerField(default=8000),
            preserve_default=False,
        ),
    ]
