# Generated by Django 6.1.1 on 2026-10-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_rename_price_merch_adult_price_merch_child_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='color',
            field=models.CharField(default='black', max_length=50),
            preserve_default=False,
        ),
    ]
